-- MySQL Script generated by MySQL Workbench
-- Tue Aug 13 13:17:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema curse_analytics
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `curse_analytics` ;

-- -----------------------------------------------------
-- Schema curse_analytics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `curse_analytics` DEFAULT CHARACTER SET utf8mb4 ;
USE `curse_analytics` ;

-- -----------------------------------------------------
-- Table `curse_analytics`.`stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curse_analytics`.`stats` ;

CREATE TABLE IF NOT EXISTS `curse_analytics`.`stats` (
  `statDate` DATE NOT NULL,
  `projectId` INT(11) NOT NULL,
  `projectName` VARCHAR(255) NULL DEFAULT NULL,
  `projectPoints` DOUBLE NULL DEFAULT NULL,
  `projectTotalDownloads` INT(11) NULL DEFAULT NULL,
  `projectDailyDownloads` INT(11) NULL DEFAULT NULL,
  `projectDailyUniqueDownloads` INT(11) NULL DEFAULT NULL,
  `projectDailyTwitchDownloads` INT(11) NULL DEFAULT NULL,
  `projectDailyCurseForgeDownloads` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`statDate`, `projectId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
