{
 "title": "Curse Analytics",
 "time": { "from": "now/M", "to": "now/M" },
 "panels": [
  {
   "title": "Total Downloads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  statDate AS \"time\",\n  projectName AS metric,\n  projectTotalDownloads\nFROM stats\nWHERE\n  $__timeFilter(statDate)\nORDER BY statDate"
    }
   ]
  },
  {
   "title": "Points",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Points" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  statDate AS \"time\",\n  projectName AS metric,\n  projectPoints\nFROM stats\nWHERE\n  $__timeFilter(statDate) and projectPoints > 0\nORDER BY statDate"
    }
   ]
  },
  {
   "title": "Daily Downloads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  statDate AS \"time\",\n  projectName AS metric,\n  projectDailyDownloads\nFROM stats\nWHERE\n  $__timeFilter(statDate)\nORDER BY statDate"
    }
   ]
  },
  {
   "title": "Platform Downloads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  statDate AS \"time\",\n  projectName AS metric,\n  projectDailyTwitchDownloads as \"Twitch\",\n  projectDailyCurseForgeDownloads as \"Curseforge\"\nFROM stats\nWHERE\n  $__timeFilter(statDate)\nORDER BY statDate\n"
    }
   ]
  },
  {
   "title": "Downloads over time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  statDate AS \"time\",\n  sum(projectDailyDownloads) as daily, \n sum(projectDailyDownloads)/24 as hourly\nFROM stats\n\nWHERE\n  $__timeFilter(statDate)\n   group by statDate\n"
    }
   ]
  },
  {
   "title": "Unique Downloads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  statDate AS \"time\",\n  projectName AS metric,\n  projectDailyUniqueDownloads\nFROM stats\nWHERE\n  $__timeFilter(statDate)\nORDER BY statDate"
    }
   ]
  },
  {
   "title": "Downloads per month",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  statDate AS \"time\",\n  sum(projectDailyDownloads) as downloads,\n  sum(projectPoints) as points\nFROM stats\n\nWHERE\n  $__timeFilter(statDate) and projectPoints > 0\n   group by month(statDate)\n   order by statDate"
    }
   ]
  }
 ]
}